name: Run Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  PYENV_ROOT: /home/runner/.pyenv

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [2.7, 3.11]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pyenv
        run: |
          curl https://pyenv.run | bash
          echo "$PYENV_ROOT/bin" >> $GITHUB_PATH
          echo "$PYENV_ROOT/shims" >> $GITHUB_PATH

      - name: Install Python ${{ matrix.python-version }}
        run: |
          pyenv install ${{ matrix.python-version }}
          pyenv global ${{ matrix.python-version }}
          pip install --upgrade pip setuptools wheel

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          # afegeix aquí qualsevol altre requeriment, si cal
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run tests with pytest
        run: |
          pytest -v
